name: Tablecloth
version: '${projectVersion}'
main: ru.ckateptb.tablecloth.Tablecloth
load: STARTUP
api-version: 1.17
depend: [ ProtocolLib, CommandAPI ]
softdepend: [  ]
authors: [ CKATEPTb ]
description: API for my plugins, with built-in spring ioc
